dist: xenial
sudo: true
language: python
python:
- '3.6'
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- bash ntsqlite/sql/build.sh
- mkdir -p ~/.nutra/nt
- mv ntsqlite/sql/nt.sqlite ~/.nutra/nt
install:
- pip install -r requirements.txt
script:
- pytest test_*.py -v -s
notifications:
  slack:
    secure: I0gwjaA3Iy27S9yat3uPuyMOKBwbexb//9tpzRxVE49GapeKTC7xhoE20VpCRCj937t9aY6p2kWqGISzrQIK6UKGlDv3okzyH3QB7g8XJ3ewP17AUOzHx4XsZUtiltVS60Y18sf93yWKacL2shOSKDMXacWl1S+heWuq4HyZxrTbNLNpBjkZ/2vJ23kQjSzIRLg9+wmSc80IbqMXoNjOp8vl4V4fyDvSZ8CRnX5Yh668tHY5NAD6MnMOPAbZIBV1bIqDwwWHO1Rt3aCFSXqQmXuu9Vo+EYrq++N0Pk6xF2vqbeNo112R3VC7sN47WcFEW5WKoAjNMCwbLyPDjV5YOvbxxvdNuicbgC438DmCz4Zd2IkKb6taOgfhclY0PIp6EusdfmRqFvWePjTqIA+MYnm1NESvOavFJGhZwN4eTrFu8/zZpcdtknAbVjAd04AePf7x9HUDE6BKO4+3c7a30YP5HfbdK37U7hF+OE7qyZ0xpFsM1WUWgZO+dBcKorZW20mFIy+j8v1spaYgL0PloXsrtEk6rjD0rrhiPSYGVGSCPQl3ymEu3ar3T9/5Pr4z6hm9xssg5CiccIRossErLRbiY1RWwBmlwrkykEk0UYe66qTVC149ZVlHfy1iWyokw+6Pv+HPaYdOeLeEFAOxpqzodeRh+bXJoXH3eemAxls=
