#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 28 22:25:38 2018

@author: shane
"""

import sys
import argparse
from core import db, user


class fmt:
    BOLD = '\033[1m'
    END = '\033[0m'


usage = f"""Nutritracker helps you stay fit and healthy.
Version 0.0.1


Usage: {fmt.BOLD}nutri <command> {fmt.END}

Commands:
    {fmt.BOLD}user{fmt.END}                create, edit and switch users
    {fmt.BOLD}db{fmt.END}                  import, edit and verify databases
    {fmt.BOLD}field{fmt.END}               import, pair and manage fields
    {fmt.BOLD}recipe{fmt.END}              create, edit and view foods and recipes
    {fmt.BOLD}search{fmt.END}              search databases or recipes
    {fmt.BOLD}add{fmt.END}                 add foods or items to daily log
    {fmt.BOLD}log{fmt.END}                 show previous meals and summary
    {fmt.BOLD}sync{fmt.END}                sync android device
    {fmt.BOLD}contrib{fmt.END}             rank contributions"""


def main():
    """ Parses the args and hands off to submodules """
    for i, arg in enumerate(sys.argv):
        if arg == __file__:
            if len(sys.argv) == 1:
                print(usage)
            else:
                continue
        elif hasattr(cmdmthds, arg):
            getattr(cmdmthds, arg).mthd()
            break
        else:
            print(f"nutri: '{arg}' is not a nutri command.  See 'nutri help'.")
            break


class cmdmthds:
    """ Where we keep the `cmd()` methods && help info"""

    class user:
        _help = 'user help'

        def mthd():
            print('hi user()')

    class help:
        _help = usage

        def mthd():
            print(usage)

#<editor-fold desc="Description">
#     # Set up the parser
#     parser = argparse.ArgumentParser()
#     #parser.description = 'hi'
#     #parser.epilog = 'bye'

#     # Add arguments
#     parser.add_argument('--version', '-v', action='version', version='Nutritracker version 0.0.1')

#     # Subparser
#     subparsers = parser.add_subparsers(title='subcommands')
#     parser_user = subparsers.add_parser('user', help='user help')
#     parser_user.add_usage
#     parser_user.add_argument('-u', dest='user', help='user subcommand help')
#     parser_db = subparsers.add_parser('db', help='db help')
#     # parser_user = subparsers.add_parser('user', help='user help')
#     # parser_db = subparsers.add_parser('db', help='db help')
#     parser_field = subparsers.add_parser('field', help='field help')
#     parser_recipe = subparsers.add_parser('recipe', help='recipe help')
#     parser_search = subparsers.add_parser('search', help='search help')
#     parser_add = subparsers.add_parser('add', help='add help')
#     parser_log = subparsers.add_parser('log', help='log help')
#     parser_sync = subparsers.add_parser('sync', help='sync help')


# endregion
#</editor-fold>

if __name__ == "__main__":
    main()
